apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA-env1
          artifact-id: c37604d9-6ec5-4091-a26b-e06073091416
          target-environment: qatest
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA-env2
          artifact-id: c37604d9-6ec5-4091-a26b-e06073091416
          target-environment: Automation QA

